### ISSUE TITLE
Jedi Knight Sentinel CanNotBeDetermined

### ISSUE THREAD

**Issue by jkrizz** [aevitas/BuddyWing.DefaultCombat#17]
2016-01-20 15:34:18,670 [1] INFO  Log - Starting Buddy Wing v1.0.1257.822
2016-01-20 15:34:21,327 [6] INFO  Log - Logging in...
2016-01-20 15:34:21,552 [6] INFO  Log - //removed
2016-01-20 15:34:21,553 [6] INFO  Log - Login Success!
2016-01-20 15:34:22,673 [7] INFO  Log - //removed
2016-01-20 15:34:22,674 [7] INFO  Log - //removed
2016-01-20 15:34:22,675 [7] INFO  Log - App Path: //removed
2016-01-20 15:34:26,854 [7] INFO  Log - User is a Knight
2016-01-20 15:34:27,721 [7] INFO  Log - Advanced Class: Sentinel / Discipline: CanNotBeDetermined
2016-01-20 15:34:27,722 [7] INFO  Log - Routine Path: Routines
2016-01-20 15:34:28,830 [7] INFO  Log - Medpac  Created!
2016-01-20 15:34:28,855 [7] INFO  Log - [DefaultCombat] Level: 17
2016-01-20 15:34:28,855 [7] INFO  Log - [DefaultCombat] Class: Knight
2016-01-20 15:34:28,856 [7] INFO  Log - [DefaultCombat] Advanced Class: Sentinel
2016-01-20 15:34:28,874 [7] INFO  Log - [DefaultCombat] Discipline: CanNotBeDetermined
2016-01-20 15:34:28,893 [7] ERROR Log - Unhandled exception during init:
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DefaultCombat.Core.RotationFactory.Build(String name) in //removed\Buddywing\Routines\DefaultCombat\Core\RotationFactory.cs:line 54
   at DefaultCombat.DefaultCombat.Initialize() in //removed\Buddywing\Routines\DefaultCombat\DefaultCombat.cs:line 69
   at Buddy.CommonBot.RoutineManager.set_Current(ICombat value)
   at Buddy.CommonBot.BotMain.SetCurrentCombatRoutine()
   at Buddywing.MainWindow.?????????????????????????????????????????()
2016-01-20 15:34:28,894 [7] INFO  Log - Buddy Wing: The Old Robot is ready!

**Comment by Markeeen** [comment]
Uhm, did you chose a discipline?

**Comment by jkrizz** [comment]
My chosen discipline is Watchman, I'm currently level 17.

**Comment by Markeeen** [comment]
Your client language? 

It's weird that you get CanNotBeDetermined for your chosen discipline, i can load Watchman without issues.

try to re download buddywing from

http://updates.buddyauth.com/GetNewest?filter=Buddywing

and reinstall/unzip.

**Comment by jkrizz** [comment]
I downloaded from the link you added and ran the new copy immediately without touching anything.  It gives the same error as my original post.  Attached is my proficiency tab in game.  My client language is English.
![swtor](https://cloud.githubusercontent.com/assets/12344914/12493651/002c2e18-c054-11e5-9e7d-ad088f8c50f1.png)

**Comment by aevitas** [comment]
This is interesting. We may have to run some additional diagnostics to be able to determine why your discipline isn't being picked up correctly. As @Markeeen said, it is actually supported.

**Comment by jkrizz** [comment]
Just to add, logging onto my seer or my inquisitor both have their disciplines detected correctly.  The seer is 26 and the inquisitor is 50.

**Comment by Markeeen** [comment]
Can you switch to Combat and try if that works for you? It's better for leveling (it's a burst spec) and you can at least play a good dps spec until this is sorted out.

**Comment by jkrizz** [comment]
I switched to Combat and the bot picked up that discipline properly.  I'll use Combat for now.  Thanks!

**Comment by Logandros** [comment]
Issue has been resolved
